<script language="JavaScript" type="text/javascript">
<!--
var theImages = new Array();
theImages[0] = '/lawis/eyh/images/graphic1.jpg'
theImages[1] = '/lawis/eyh/images/graphic2.jpg'
theImages[2] = '/lawis/eyh/images/graphic3.jpg'
theImages[3] = '/lawis/eyh/images/graphic4.jpg'
theImages[4] = '/lawis/eyh/images/graphic5.jpg'
theImages[4] = '/lawis/eyh/images/graphic6.jpg'
theImages[5] = '/lawis/eyh/images/graphic7.jpg'

var j = 0;
var p = theImages.length;
var preBuffer = new Array();
for (i= 0; i<p; i++){
   preBuffer[i] = new Image()
   preBuffer[i].src = theImages[i]
}
var whichImage = Math.round(Math.random()*(p-1));
function showImage(){
document.write('<img src="'+theImages[whichImage]+'" alt="EYH images" align="center"  hspace="0" border="0" />');
}
// -->
</script>
<div class="col2">
                <div class="block">
                    <h4>Resources</h4>
                   <div align="center">
  <script language="JavaScript" type="text/javascript">showImage();</script>
</div>
                    <br /><h2>For Attendees</h2>
                    <p><a href="http://nmnwse.org/career.htm">Careers: Exploring the Possibilities</a><br />
                      <br />
                      <a href="docs/EYH09SponsorLtr.pdf">Invitation (pdf)</a><br />
                      <br />
                      <a href="docs/09EYHSupportKimThomas.pdf">STB Sponsor Letter (pdf)</a></p>
                    <p><a href="map_directions.shtml">Map and Directions</a></p>
                  <p><a href="schedule.shtml">Schedule</a></p>
                  <p><a href="docs/EYH09 StudentRegF12409.pdf">Printable Student Registration (pdf) </a></p>
                  <p><a href="docs/EYH09 SponsorReg.pdf">Printable Sponsor/Teacher Registration  (pdf ) </a></p>
                  <p><a href="http://nmnwse.org/eyh/">NMNWSE EYH conferences</a></p>
                <hr size="1" />

                    <h2><br />
                    For Volunteers</h2>
                    <p><a href="planning_meetings.shtml">Planning Meetings </a></p>
                  <p><a href="workshop_presenters.shtml">Workshop Presenters </a></p>
                  <p><a href="gofers.shtml">Gofers</a> </p>
                  <p><a href="http://enterprise.lanl.gov/forms/704.pdf">LANL Community Service Request</a><br />
                    <br />
                    <a href="student_evaluation_summary.shtml">Student Evaluation Summary </a></p>
                    <p><a href="docs/EYH09SponsorLtr.pdf"></a></p>
                    <p><a href="docs/09EYHSupportKimThomas.pdf"></a></p>
             </div>
           </div>