<script language="JavaScript" type="text/javascript">
<!--
var theImages = new Array();
theImages[0] = '/lawis/eyh/images/graphic1.jpg'
theImages[1] = '/lawis/eyh/images/graphic2.jpg'
theImages[2] = '/lawis/eyh/images/graphic3.jpg'
theImages[3] = '/lawis/eyh/images/graphic4.jpg'
theImages[4] = '/lawis/eyh/images/graphic5.jpg'
theImages[4] = '/lawis/eyh/images/graphic6.jpg'
theImages[5] = '/lawis/eyh/images/graphic7.jpg'

var j = 0;
var p = theImages.length;
var preBuffer = new Array();
for (i= 0; i<p; i++){
   preBuffer[i] = new Image()
   preBuffer[i].src = theImages[i]
}
var whichImage = Math.round(Math.random()*(p-1));
function showImage(){
document.write('<img src="'+theImages[whichImage]+'" alt="EYH images" align="center"  hspace="0" border="0" />');
}
// -->
</script>
<div class="col2">
                <div class="block">
                    <h4>Resources</h4>
                   <div align="center">
  <script language="JavaScript" type="text/javascript">showImage();</script>
</div>
                    <br /><h2>For Attendees</h2>
                    <p>
                      <br />
                      <a href="docs/eyh_invite_2016.pdf">Invitation</a><br /></p>
		   <p><a href="docs/EYH16_Program_final.pdf">EYH16 Program</a></p>
                    <p><a href="map_directions.shtml">Map and Directions</a></p>
                  <p><a href="attendees.shtml">EYH16 Schedule</a><br />
                    <br />
                  <a href="registration.shtml">EYH16 Registration</a>
		 <p> <a href="docs/EYH Liability Form 2016.pdf">EYH16 Liability Form</a></p>
		  <br />
		 <p><a href="donations.shtml">EYH16 Sponsors</a></p>
                  <br />
                  <p><a href="http://nmnwse.org/eyh/">NMNWSE EYH conferences</a></p>
                <hr size="1" />

                    <h2><br />
                    For Volunteers</h2>
            	<p>EYH is run entirely by volunteers!  Please see the <a href="volunteers.shtml">volunteer page</a> to see how you can help.
             </div>
           </div>
